[tool.black]
line-length = 88
target-version = ['py39']
include = '\.py$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | __pycache__
  | .*\.pyc
  | .*\.pyo
  | .*\.pyd
  | .*\.egg-info
)/
'''

[tool.isort]
profile = "black"
